import Chapter from '../pages/Chapter.vue'
import Login from '../pages/Login.vue'
export default 
[   
    {
        path:'/',
        redirect:'/books'
    },
    {
        path:'/admin',
        component:()=>import('../pages/Admin.vue'),
        children:[
        {
            path:'/edit',
            name:'edit',
            component:()=>import('../components/Edit.vue'),
        },
        {
            path:'/favorites',
            name:'favorites',
            component:()=>import('../components/Favorites.vue')
        },]
    },
    {
        path:'/list',
        name:'list',
        component:()=>import('../pages/List.vue')        
    },
    {
        path:'/fall',
        name:'fall',
        component:()=>import('../pages/Fall.vue')        
    },
    {
        path:'/read',
        name:'read',
        component:()=>import('../pages/Read.vue')        
    },
    {
        path:'/ndetail',
        name:'ndetail',
        component:()=>import('../pages/Ndetail.vue')        
    },
    {
        path:'/search',
        name:'search',
        component:()=>import('../pages/Search.vue')        
    },
    {
        path:'/bookdetail',
        name:'bookdetail',
        component:()=>import('../pages/BookDetail.vue')        
    },
    {
        path:'/books',
        name:'books',
        component:()=>import('../pages/Books.vue')
    },
    {
        path:'/hpic',
        name:'hpic',
        component:()=>import('../pages/Hpic.vue')
    },
    {
        path:'/chapter',
        name:'chapter',
        component:Chapter   
    },
    {
        path:'/login',
        name:'login',
        component:Login
    }
]